namespace: escalate
name: raspberry
version: 0.0.0
readme: README.md
authors:
  - Felix Boerner
description: A collection of roles for managing Raspberry Pi OS (Debian Bookworm) and various container-based services (Docker).
license_file: LICENSE
# Only 20 tags are allowed
tags:
  - backup
  - container
  - cron
  - dns
  - docker
  - grafana
  - homeassistant
  - influxdb
  - loki
  - openssh
  - pi
  - promtail
  - raspberry
  - raspberrypi
  - ssh
  - sshd
  - systemd
  - telegraf
  - timesyncd
  - traefik
dependencies:
  # https://galaxy.ansible.com/ui/repo/published/ansible/posix/
  ansible.posix: ">=2.0.0,<3.0.0"
  # https://galaxy.ansible.com/ui/repo/published/community/docker/
  community.docker: ">=4.0.0,<5.0.0"
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  community.general: ">=11.0.0,<12.0.0"
repository: https://github.com/escalate/ansible-collection-raspberry
documentation: https://github.com/escalate/ansible-collection-raspberry
homepage: https://github.com/escalate/ansible-collection-raspberry
issues: https://github.com/escalate/ansible-collection-raspberry/issues
build_ignore:
  - .github
