namespace: escalate
name: raspberry
version: NEXT_VERSION
readme: README.md
authors:
  - Felix Boerner
description: |
  This collection includes roles for setting up a Raspberry Pi, installing Docker, and managing various services.
  It is designed to simplify the deployment and management of applications on Raspberry Pi devices.
  The collection is compatible with the lastest Raspberry Pi OS version.
license_file: LICENSE
tags:
  - raspberry
  - pi
  - raspberrypi
  - cmdline
  - common
  - hostname
  - timezone
  - apt
  - docker
  - systemd
  - container
  - coredns
  - dns
dependencies:
  # https://galaxy.ansible.com/ui/repo/published/ansible/posix/
  ansible.posix: ">=2.0.0,<3.0.0"
  # https://galaxy.ansible.com/ui/repo/published/community/docker/
  community.docker: ">=4.6.0,<5.0.0"
  # https://galaxy.ansible.com/ui/repo/published/community/general/
  community.general: ">=11.0.0,<12.0.0"
repository: https://github.com/escalate/ansible-collection-raspberry
documentation: https://github.com/escalate/ansible-collection-raspberry
homepage: https://github.com/escalate/ansible-collection-raspberry
issues: https://github.com/escalate/ansible-collection-raspberry/issues
build_ignore:
  - .github
