namespace: escalate
name: raspberry
version: 1.0.0
readme: README.md
authors:
  - Felix Boerner
description: your collection description
license:
  - MIT
license_file: LICENSE
tags:
  - raspberry
  - pi
  - raspberrypi
dependencies: {}
repository: https://github.com/escalate/ansible-collection-raspberry
documentation: https://github.com/escalate/ansible-collection-raspberry
homepage: https://github.com/escalate/ansible-collection-raspberry
issues: https://github.com/escalate/ansible-collection-raspberry/issues
build_ignore:
  - .github
